[movieroom]
title = "방구석1열"
url = "https://program.naver.com/p/8121580/clip"
entrySelector = "li.ClipCard_item__1ly4h"
titleSelector = "strong.ClipCard_title__2I1pd"
linkSelector = "a.ClipCard_link__2XpqM"
imageSelector = "img.ClipCard_img__2XgXF"
contentSelector = "span.ClipCard_time__128vc"
waitUntil = "networkidle"
onFail = "stale"

[m_mbc_video_clip]
title = "출발! 비디오 여행 모바일 ─ 스페셜영상"
url = "https://m.imbc.com/VOD/SketchList/1000827100000100000?type=3"
entrySelector = "div.documentation ul.wrap-item li.item"
titleSelector = "div.title span.tit"
linkSelector = "a"
contentSelector = "div.meta span.date"
imageSelector = "div.w_photo img"
waitUntil = "networkidle"

[kbs_ilovemovie_replay]
title = "영화가 좋다 ─ 다시보기"
url = "https://program.kbs.co.kr/2tv/enter/ilovemovie/pc/list.html?smenu=c2cc5a"
entrySelector = "ul.comp01-list li"
titleSelector = "span.des.ng-binding.ng-scope"
linkSelector = "a.listFullVod"
imageSelector = "img"
contentSelector = "span.episode.ng-binding.ng-scope"
waitUntil = "networkidle"
onFail = "stale"
